//! Build script: (1) picks the newest vendored Flux models snapshot and
//! exports it as `FLUX_MODELS_FIXTURE` (file name only) so the crate can
//! embed the catalog body at compile time (embedded is the shipped-binary
//! fallback; the on-disk fixture stays the primary source in dev — see
//! flux_models.rs); (2) generates the static provider table (C8 §2) from
//! `data/providerCatalog.vendored.json` into `$OUT_DIR/provider_catalog.rs`,
//! validated through the SAME schema module the tests use — an invalid
//! catalog fails the build, never silently codegens.
use std::path::Path;

#[path = "src/catalog_schema.rs"]
mod catalog_schema;

fn main() {
    let dir = Path::new("fixtures-flux/models");
    println!("cargo:rerun-if-changed={}", dir.display());
    let mut files: Vec<_> = std::fs::read_dir(dir)
        .expect("vendored flux models fixture dir must exist")
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with("_models.json"))
        .collect();
    files.sort();
    let newest = files
        .pop()
        .expect("at least one *_models.json fixture must exist");
    println!("cargo:rustc-env=FLUX_MODELS_FIXTURE={newest}");

    generate_provider_catalog();
}

/// C8 §2: the vendored JSON is the SOLE endpoint authority. Codegen is
/// deterministic (input-order preserved — the catalog's row order IS the
/// routing/advertisement tie-break order) and validated; the generated
/// table is pinned by tests/golden/provider_catalog.golden.rs and the input
/// by the SHA-256 drift test in tests/provider_catalog.rs.
fn generate_provider_catalog() {
    let path = "data/providerCatalog.vendored.json";
    println!("cargo:rerun-if-changed={path}");
    let text =
        std::fs::read_to_string(path).expect("vendored provider catalog must exist and be utf-8");
    let catalog = catalog_schema::validate_catalog_json(&text)
        .unwrap_or_else(|e| panic!("vendored provider catalog is invalid: {e}"));

    let mut out = String::new();
    out.push_str(
        "// @generated by nano-model/build.rs from data/providerCatalog.vendored.json — do not edit.\n",
    );
    out.push_str("pub static PROVIDERS: &[ProviderSpec] = &[\n");
    for p in &catalog.providers {
        let wire = match p.wire.as_str() {
            catalog_schema::WIRE_OPENAI_COMPLETIONS => "WireKind::OpenAiCompletions",
            catalog_schema::WIRE_ANTHROPIC_MESSAGES => "WireKind::AnthropicMessages",
            other => panic!("validated catalog carried unknown wire {other:?}"),
        };
        out.push_str("    ProviderSpec {\n");
        out.push_str(&format!("        id: {:?},\n", p.id));
        out.push_str(&format!("        display_name: {:?},\n", p.display_name));
        out.push_str(&format!("        base_url: {:?},\n", p.base_url));
        out.push_str(&format!("        wire: {wire},\n"));
        out.push_str(&format!("        api_path: {:?},\n", p.api_path));
        out.push_str(&format!("        env_var: {:?},\n", p.env_var));
        out.push_str(&format!(
            "        bearer_env: {:?},\n",
            catalog_schema::bearer_env_name(&p.id)
        ));
        out.push_str(&format!(
            "        bearer_expires_env: {:?},\n",
            catalog_schema::bearer_expires_env_name(&p.id)
        ));
        out.push_str(&format!("        proven: {},\n", p.proven));
        out.push_str("    },\n");
    }
    out.push_str("];\n");

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR is set for build scripts");
    std::fs::write(Path::new(&out_dir).join("provider_catalog.rs"), out)
        .expect("write generated provider catalog");
}
