//! The vendored provider catalog (C8 §2) — the SOLE authority for
//! `base_url` / `wire` / `api_path` / credential env-var names. The table is
//! codegenerated by `build.rs` from `data/providerCatalog.vendored.json`
//! (validated by `catalog_schema`, pinned by a SHA-256 drift test and a
//! golden file). The runtime `WAYLAND_NANO_PROVIDERS` payload may only
//! REFERENCE these ids — it can never introduce or redirect an endpoint.

/// The wire surface a provider speaks.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WireKind {
    /// OpenAI chat-completions (`POST {base_url}{api_path}`, Bearer auth).
    OpenAiCompletions,
    /// Anthropic messages (`POST {base_url}{api_path}`, x-api-key auth).
    AnthropicMessages,
}

/// One provider's static routing row. All fields come from the vendored
/// catalog; `bearer_env` / `bearer_expires_env` are derived at codegen time
/// from the id via the §6.3 normalization (collisions rejected by schema
/// validation).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ProviderSpec {
    pub id: &'static str,
    pub display_name: &'static str,
    pub base_url: &'static str,
    pub wire: WireKind,
    pub api_path: &'static str,
    /// Canonical API-key env var (names EXACTLY as Desktop injects them).
    pub env_var: &'static str,
    /// Env var carrying the injected short-lived OAuth access token.
    pub bearer_env: &'static str,
    /// Env var carrying the bearer's `expires_at_unix_secs` metadata.
    pub bearer_expires_env: &'static str,
    /// Live-proof gate (Q3): only `proven` providers are routable. The
    /// OpenAI-compat set flips to true together once ONE compat provider
    /// passes the live proof; `anthropic` and `google-gemini` each need
    /// their own live smoke. Unproven providers fail `set_model` with the
    /// typed `provider_unproven` error, never a silent fallback.
    pub proven: bool,
}

include!(concat!(env!("OUT_DIR"), "/provider_catalog.rs"));

/// Look up a provider by its catalog id.
pub fn provider_by_id(id: &str) -> Option<&'static ProviderSpec> {
    PROVIDERS.iter().find(|p| p.id == id)
}

/// Re-exported so callers compute env names without re-implementing the
/// normalization (and colliding with the codegen's derivation).
pub use crate::catalog_schema::normalize_provider_id;

/// The Flux Router row — the v1 primary provider (bare model ids,
/// three-source credential resolution via `flux_key`).
pub fn flux_router() -> &'static ProviderSpec {
    provider_by_id("flux-router").expect("vendored catalog always carries flux-router")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_table_matches_schema_invariants() {
        // The runtime view of the codegen: ids unique, wires map to the
        // closed enum, https base urls, normalization round-trips.
        let mut ids = std::collections::BTreeSet::new();
        for p in PROVIDERS {
            assert!(ids.insert(p.id), "duplicate id {}", p.id);
            assert!(p.base_url.starts_with("https://"), "{} base_url", p.id);
            assert!(p.api_path.starts_with('/'), "{} api_path", p.id);
            assert_eq!(
                p.bearer_env,
                crate::catalog_schema::bearer_env_name(p.id),
                "{} bearer env derivation",
                p.id
            );
            assert!(!p.display_name.is_empty());
        }
    }

    #[test]
    fn flux_router_is_present_and_proven() {
        let flux = flux_router();
        assert_eq!(flux.wire, WireKind::OpenAiCompletions);
        assert!(flux.proven, "the v1 primary wire stays routable");
        assert_eq!(flux.base_url, crate::flux_common::FLUX_BASE);
    }

    #[test]
    fn proven_state_is_explicit_per_provider() {
        // Q3: providers ship gated until a live end-to-end proof flips them.
        // 2026-08-12: the live provider-proof matrix (shared/reviews/RC/
        // evidence/provider-live-proofs/) proved these 9 end-to-end with real
        // keys — both wire surfaces, incl. the anthropic-native arm.
        for id in [
            "openai",
            "anthropic",
            "google-gemini",
            "deepseek",
            "groq",
            "cerebras",
            "together",
            "fireworks",
            "moonshot",
            "xai",
            "cohere",
            "mistral",
            "perplexity",
        ] {
            let spec = provider_by_id(id).expect("catalog carries the v1 set");
            assert!(spec.proven, "{id} was live-proven on 2026-08-12");
        }
        // Still gated: no working key has proven these end-to-end. A missing
        // flag is a build-time error, not a silent default.
        for id in ["openrouter", "nvidia", "minimax"] {
            let spec = provider_by_id(id).expect("catalog carries the v1 set");
            assert!(!spec.proven, "{id} awaits its live proof");
        }
    }
}
