[package]
name = "nano-tools"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
dunce = "1"
globset = "0.4"
regex = "1"
nano-core = { path = "../nano-core" }
thiserror = "2"

[dev-dependencies]
pretty_assertions = "1"
tempfile = "3"
