[package]
name = "nano-agent"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
nano-skills = { version = "0.1.0", path = "../nano-skills" }
nano-mcp = { version = "0.1.0", path = "../nano-mcp" }
nano-tools = { version = "0.1.0", path = "../nano-tools" }
async-trait = "0.1"
nano-model = { version = "0.1.0", path = "../nano-model" }
nano-session = { version = "0.1.0", path = "../nano-session" }
tokio = { version = "1", features = ["macros", "rt", "time"] }
serde_json = "1"

[dev-dependencies]
nano-core = { version = "0.1.0", path = "../nano-core" }
nano-egress = { version = "0.1.0", path = "../nano-egress" }
tempfile = "3"
pretty_assertions = "1"
